version: "3.3"
services:
  api:
    build: ./api
    container_name: api
    restart: always
    networks:
        - main-network
    ports: 
        - "5000:5000"
    env_file:
        - ./api/.env
    environment:
        - PORT=5000
        - PETERPORTAL_MAIN_ES=https://es:9200
        - MONGO_URL=mongodb://mongo:27017/peterPortalDB
    depends_on:
        - es
        - mongo
  site:
    build: ./site
    container_name: site
    restart: always
    networks:
        - main-network
    ports: 
        - "3000:3000"
    environment:
        - PORT=3000
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo:/data/db
    networks:
      - main-network
    ports:
      - "27017:27017"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: es
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    networks:
      - main-network
    expose:
      - "9200"
    ports:
      - "9200:9200"
  es-seed:
    build: ./docker/es-seed
    networks:
      - main-network
    depends_on: 
      - es
volumes:
  mongo:
  es:
networks:
  main-network: