service: peterportal-core
useDotenv: true

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: prod
  apiGateway:
    binaryMediaTypes:
      - 'image/*'

functions:
  app:
    handler: dist/app.handler
    events: 
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY
