name: Clean up PR

on:
  pull_request:
    types: [closed]
    branches:
      - master

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  clean-up-pr:
    runs-on: ubuntu-latest
    env:
      # need to set to false, otherwise react warnings will be treated as errors
      STAGING_PREFIX: ${{ github.event_name == 'pull_request' && format('staging-{0}.', github.event.pull_request.number) || '' }}
      STAGE_NAME: ${{ github.event_name == 'pull_request' && format('staging-{0}', github.event.pull_request.number) || 'prod' }}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Dump Environment Variables
        id: dump-env-variables
        run: |
          cd api && printf "STAGING_PREFIX=$STAGING_PREFIX\n \
            STAGE_NAME=$STAGE_NAME" > .env

      - name: Remove Serverless stack
        uses: serverless/github-action@v3.1
        if: ${{ success() || ( cancelled() && steps.dump-env-variables.outcome == 'success' ) }}
        with:
          args: >
            -c "cd api && 
            serverless plugin install --name serverless-dotenv-plugin && 
            serverless plugin install --name serverless-domain-manager && 
            serverless remove"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
